In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("aa_dataset-tickets-multi-lang-5-2-50-version.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  object
 1   body      28587 non-null  object
 2   answer    28580 non-null  object
 3   type      28587 non-null  object
 4   queue     28587 non-null  object
 5   priority  28587 non-null  object
 6   language  28587 non-null  object
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  object
 9   tag_2     28574 non-null  object
 10  tag_3     28451 non-null  object
 11  tag_4     25529 non-null  object
 12  tag_5     14545 non-null  object
 13  tag_6     5874 non-null   object
 14  tag_7     2040 non-null   object
 15  tag_8     565 non-null    object
dtypes: int64(1), object(15)
memory usage: 3.5+ MB

In [7]:
df.describe()

            version
count  28587.000000
mean     278.382027
std      165.962935
min       51.000000
25%       52.000000
50%      400.000000
75%      400.000000
max      400.000000

In [8]:
df = df[df["language"] != "de"]

In [9]:
df.head()

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Thank you for your inquiry. Please specify whi...,Request,Technical Support,high,en,51,Feature,Product,Documentation,Feedback,NaN,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16338 entries, 1 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   13731 non-null  object
 1   body      16338 non-null  object
 2   answer    16335 non-null  object
 3   type      16338 non-null  object
 4   queue     16338 non-null  object
 5   priority  16338 non-null  object
 6   language  16338 non-null  object
 7   version   16338 non-null  int64
 8   tag_1     16338 non-null  object
 9   tag_2     16332 non-null  object
 10  tag_3     16269 non-null  object
 11  tag_4     14627 non-null  object
 12  tag_5     8416 non-null   object
 13  tag_6     3370 non-null   object
 14  tag_7     1134 non-null   object
 15  tag_8     281 non-null    object
dtypes: int64(1), object(15)
memory usage: 2.1+ MB

In [11]:
df = df.drop(columns=["language", "version"])

In [12]:
df["body"] = (
    df["body"]
      .str.replace(r"\\n\\n", " ", regex=True)
      .str.replace(r"\\n", " ", regex=True)
      .str.strip()
)

In [13]:
df["answer"] = (
    df["answer"]
      .str.replace(r"\\n\\n", " ", regex=True)
      .str.replace(r"\\n", " ", regex=True)
      .str.strip()
)

In [14]:
df["subject"] = (
    df["subject"]
      .str.replace(r"\\n\\n", " ", regex=True)
      .str.replace(r"\\n", " ", regex=True)
      .str.strip()
)

In [15]:
df["answer"] = (
    df["answer"]
      .str.replace(r"\s*,?\s*<name>\s*,?\s*", " ", regex=True)
      .str.replace(r"\s+([.,!?;:])", r"\1", regex=True)
      .str.replace(r"\s{2,}", " ", regex=True)   # collapse double spaces
      .str.strip()
)

In [16]:
df.head()

,subject,body,answer,type,queue,priority,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
1,Account Disruption,"Dear Customer Support Team, I am writing to re...",Thank you for reaching out. We are aware of th...,Incident,Technical Support,high,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team, I hope this messag...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team, I hope this messag...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team, I hope this message reaches...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN
5,Feature Query,"Dear Customer Support, I hope this message rea...",Thank you for your inquiry. Please specify whi...,Request,Technical Support,high,Feature,Product,Documentation,Feedback,NaN,NaN,NaN,NaN

In [17]:
df = df.drop(columns=["tag_4", "tag_5", "tag_6", "tag_7", "tag_8"])

In [18]:
df = df.rename(columns={"queue":"department"})

In [19]:
df.head()

,subject,body,answer,type,department,priority,tag_1,tag_2,tag_3
1,Account Disruption,"Dear Customer Support Team, I am writing to re...",Thank you for reaching out. We are aware of th...,Incident,Technical Support,high,Account,Disruption,Outage
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team, I hope this messag...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,Product,Feature,Tech Support
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team, I hope this messag...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,Billing,Payment,Account
4,Question About Marketing Agency Software Compa...,"Dear Support Team, I hope this message reaches...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,Product,Feature,Feedback
5,Feature Query,"Dear Customer Support, I hope this message rea...",Thank you for your inquiry. Please specify whi...,Request,Technical Support,high,Feature,Product,Documentation